# Generated by Django 6.0.2 on 2026-02-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_alter_table_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
